### ISSUE TITLE
ImportError: No module named yaml

### ISSUE THREAD

**Issue by YXGuan** [fazildgr8/ros_autonomous_slam#10]
Hi there,

I am trying to run the program on Noetic. Below is the error. Your help would be much appreciated : )

```
Traceback (most recent call last):
  File "/home/yuxiang/catkin_ws/src/ros_autonomous_slam/scripts/filter.py", line 5, in <module>
    import rospy
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 48, in <module>
    import yaml
ImportError: No module named yaml
Traceback (most recent call last):
  File "/home/yuxiang/catkin_ws/src/ros_autonomous_slam/scripts/assigner.py", line 5, in <module>
    import rospy
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 48, in <module>
    import yaml
ImportError: No module named yaml
[filter-7] process has died [pid 1950541, exit code 1, cmd /home/yuxiang/catkin_ws/src/ros_autonomous_slam/scripts/filter.py __name:=filter __log:=/home/yuxiang/.ros/log/23246bfe-bd9d-11ec-89fe-d993a19ee3f3/filter-7.log].
log file: /home/yuxiang/.ros/log/23246bfe-bd9d-11ec-89fe-d993a19ee3f3/filter-7*.log
[assigner-8] process has died [pid 1950552, exit code 1, cmd /home/yuxiang/catkin_ws/src/ros_autonomous_slam/scripts/assigner.py __name:=assigner __log:=/home/yuxiang/.ros/log/23246bfe-bd9d-11ec-89fe-d993a19ee3f3/assigner-8.log].
log file: /home/yuxiang/.ros/log/23246bfe-bd9d-11ec-89fe-d993a19ee3f3/assigner-8*.log
Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame odom at time 24.857000 according to authority unknown_publisher
         at line 278 in /home/yuxiang/catkin_ws/src/geometry2/tf2/src/buffer_core.cpp
Warning: TF_REPEATED_DATA ignoring data with redundant timestamp for frame odom at time 24.857000 according to authority unknown_publisher
         at line 278 in /home/yuxiang/catkin_ws/src/geometry2/tf2/src/buffer_core.cpp
[ WARN] [1650124346.075714987, 24.879000000]: global_costmap: Parameter "plugins" not provided, loading pre-Hydro parameters

```

**Comment by aradhyamathur** [comment]
I installed it using `pip install pyyaml` seemed to have worked that way.

**Comment by YXGuan** [comment]
> I installed it using `pip install pyyaml` seemed to have worked that way.

Sounds good, Thank you boss!

**Comment by MJ1307** [comment]
@YXGuan turtlebot not moving in RViz. Any idea
